import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Script from 'next/script'
import { CopyToClipboard } from 'react-copy-to-clipboard';
import React, { useState } from 'react';

export default function Home() {
  const [url, setUrl] = useState('');
  const [copy, setCopy] = useState(false);
  const [show, setShow] = useState(false);

  const check = (event) => {
    if (event.key === 'Enter') {
      event.preventDefault();
      const reg = RegExp(/http(?:s)?:\/\/(?:www\.)?kooapp\.com\/([a-zA-Z0-9_]+)/);
      if (!(reg.test(url))) {
        alert("Please enter Koo url!");
      }
      else {
        setShow(true);
      }
    }
  }

  const getNewCode = (ansId) => {
    const embedKooBaseURL = `https://embed.kooapp.com`;
    return `<blockquote class="koo-media" data-koo-permalink="${embedKooBaseURL}/embedKoo?kooId=${ansId}" style="background:transparent;border: medium none;padding: 0;margin: 25px auto; max-width: 550px;"></blockquote><img style="display: none; height: 0; width: 0" src="https://embed.kooapp.com/dolon.png?id=${ansId}"> <script src="${embedKooBaseURL}/embedLoader.js"></script>`;
  }

  const getKooCode = (url) => {
    const ansId = /[^/]*$/.exec(url)[0];
    const code = getNewCode(ansId);
    return (
      <div className={styles.parent}>
        <div className={styles.child1}>
          <div >
            <code style={{ color: 'black' }}>{code}</code>
          </div>
          <div >
            Click the below button to copy the code!
          </div>
          <div>
            <CopyToClipboard
              text={code}
              onCopy={() => {
                setCopy(true);
                setTimeout(() => {
                  setCopy(false);
                }, 1000);
              }}
            >
              <button
                className={[styles.shareBtn, styles.copyBtn].join(' ')}
                style={{
                  width: 'fit-content',
                  display: 'flex',
                  margin: '9px auto',
                  background: '#809b9d',
                  border: '1px solid #aeaeae',
                  borderRadius: '25px',
                  position: 'relative',
                  top: '1em',
                  color: 'white',
                }}
              >
                {copy ? (
                  'Copied...'
                ) : (
                  
                    <span> Copy code</span>
                )}
              </button>
            </CopyToClipboard>
            { }
          </div>
        </div>

<div className={styles.child2}>
            <blockquote className="koo-media" data-koo-permalink={`https://embed.kooapp.com/embedKoo?kooId=${ansId}`} style={{ background: 'transparent', border: 'medium none', padding: '0', margin: '25px auto', maxWidth: '550px' }}>
            </blockquote>
            <Script src="https://embed.kooapp.com/embedLoader.js" />
          </div>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Embed Koo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>
          <a href="#">
            <img className={styles.header} src="https://www.kooapp.com/img/logoKuSolidOutline.svg"></img>
            / Embed</a></h1>
        <h1 className={styles.title}>
          What would you like to embed?
        </h1>

        <div className={styles.page}>
          <div>
            <input list="browsers" placeholder='Enter URL' className={styles.selectdropdown}
              type="text"
              onChange={(e) => { setUrl(e.target.value);setShow(false); }}
              onKeyDown={check} />
          </div>
        </div>
        {show && getKooCode(url)}
      </main>
      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright
          <span className={styles.logo}>
            <img src="https://www.kooapp.com/img/logoKuSolidOutline.svg" alt="Koo Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}